version: '3'
services:
  zookeeper:
    image: zookeeper:local
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka-broker:
    image: kafka:local
    depends_on:
      - "zookeeper"    
    environment:
      - KAFKA_CFG_BROKER_ID=-1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  kafka-ui:
    image: obsidiandynamics/kafdrop
    container_name: kafka_ui
    depends_on:
      - "kafka-broker"
    environment:
      - KAFKA_BROKERCONNECT=kafka-broker:9092
    ports:
      - "9000:9000"
